language: python

services:
  - postgresql

python:
  - 3.8

before_install:
  - export DJANGO_SETTINGS_MODULE=bookomate.settings.travis
  - export SECRET_KEY="irrelevant"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres
  - python manage.py migrate

script:
  - python manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)
